feat: layout 및 크롬 스토리지 용어집 삭제, 추가 기능
my-hand-translator/my-hand-translator-extension pull request #5
Opened 2021-09-10 09:00 UTC by jch1223

2021-09-10 13:49 UTC, sounmind requested changes

2021-09-10 13:49 UTC, sounmind commented on src/components/EditGlossary.jsx
> +        setError(chrome.runtime.lastError.message);
에러 처리 잘해주셨네요!!
그런데 저도 하진 않았지만, 런타임의 에러 표시보다는 "데이터를 불러오는 데 실패했습니다." 같은 직접 만든 에러 메시지를 보내주는 게 좋을 것 같아요..!

2021-09-10 15:24 UTC, aidencoders commented on src/components/EditGlossary.jsx
> +import SubTitle from "./shared/SubTitle";
```suggestion
import React, { useEffect, useRef, useState } from "react";

import Button from "./shared/Button";
import Title from "./shared/Title";
import SubTitle from "./shared/SubTitle";
```

개행이 잘못된 것 같습니다 !

2021-09-10 15:24 UTC, aidencoders commented on src/components/EditGlossary.jsx
> +    chrome.storage.sync.get(["userData"], async ({ userData }) => {
아까 chromeStore 라는 유틸 함수를 만들어서 쓰셨던 것 같은데 반영이 안된거겠죠 ?

2021-09-11 04:23 UTC, jch1223 commented on src/components/EditGlossary.jsx
> +    chrome.storage.sync.get(["userData"], async ({ userData }) => {
네 유틸 함수 만들기 전에 pull request 입니다!

2021-09-11 04:29 UTC, aidencoders commented
확인했습니다!

2021-09-11 04:30 UTC, aidencoders approved these changes
확인했습니다 !

2021-09-11 04:49 UTC, sounmind requested changes

2021-09-11 04:49 UTC, sounmind commented on src/utils/chromStore.js
> +};
get이랑 set이랑 내부적으로는 같아서 수정이 필요할 것 같아요!

아마 철희님 코드 상에서 사용하지 않으셔서 못 보신 것 같은데 제 쪽에서 수정을 한 번 해볼게요..!

2021-09-11 04:56 UTC, jch1223 commented on src/utils/chromStore.js
> +};
앗 함수 안쪽은 수정했는데 이름을 수정안했네요

2021-09-11 04:56 UTC, sounmind commented on src/utils/chromStore.js
> +};
```suggestion
const set = (key, data) => {
  return new Promise((res, rej) => {
    chrome.storage.sync.set({ [key]: data }, () => {
      if (chrome.runtime.lastError) {
        rej(ERROR.SET_CHROME_STORAGE);
      }

      res(true);
    });
  });
};
```

2021-09-11 05:03 UTC, jch1223 commented on src/utils/chromStore.js
> +};
`res(data)`면 더 좋을 것 같습니다!

2021-09-11 06:32 UTC, jch1223 commented on src/utils/chromStore.js
> +};
rebase 후 수정 했습니다. 리뷰 되시면 머지 할게요!

2021-09-11 06:33 UTC, sounmind commented on src/utils/chromStore.js
> +};
오 네 이 코멘트는 보지 못했었네요!!
res(data)도 문제 없을 것 같습니다!

2021-09-11 06:34 UTC, sounmind approved these changes

2021-09-11 06:34 UTC, merged